/**
 * settings.js
 * ======================
 * The model of the WebViewer Universal Viewer can be specified here.
 * The model contains all the data necessary to load the document and setup UI state of the viewer.
 * This could contain the URL to the xod document, URL to the annotation server, the default layout modes etc.
 * 
 * This file can be defined statically on the client side, or be dynmically generated by a web server.
 * 
 * 
 */

//Optional: Provide a server url here to fetch default settings, used for model.fetch();
//window.WebViewerUniversalInstance.model.url = "http://your.server/model";
//Or provide the default settings directly here:
window.WebViewerUniversalInstance.model.set(
        {
            documentUrl: "http://pdftron.s3.amazonaws.com/files/xod/NY_fun_list.xod",
            serverUrl: "lib/html5/annotationHandler.ashx", //server script for handling annotations
            annotationUser: new PDFTron.WebViewer.User("Guest", false),
            webViewerLibPath: "lib/",
            webViewerOptions: {
                silverlightOptions: {
                    enableAnnotations: false //disable annotations if silverlight is loaded. 
                }
            }
        }
);

var browserOpened = false;
$(function() {
    $("#browseButton").click(function() {
        if (browserOpened) {
            $("#leftPanelContainer").animate({"width": "0", "opacity": 0});
        } else {

            $("#leftPanelContainer").css("position", "absolute");
            $("#leftPanelContainer").animate({"width": "250px", "opacity": 1}).queue(function(next) {
                $("#booklist").fadeIn();
                next();
            });
        }
        browserOpened = !browserOpened;
    });

    $("#booklist").on("click", "div img", function() {
        var xodSrc = $(this).attr('src').replace(".png", ".xod");
        window.WebViewerUniversalInstance.model.set({documentUrl: xodSrc});
    });
});
