var d=self,k=d.tf;(function(){function a(a){c?c.push(a):setTimeout(a,0)}var b={version:"0.7.2.0",xg:function(a){return void 0===a},wg:function(a){return null===a},oa:function(a){return null===a||void 0===a},yg:function(a){return null!==a&&void 0!==a}},c=[];d.attachEvent&&d.attachEvent("onload",function(){if(c){var a=c;c=null;for(var b=0,e=a.length;b<e;b++)a[b]()}});k||(d.tf=k={Pa:a,Hg:a});for(var e in b)k[e]=b[e]})();Object.$="Object";Object.Aa=null;Object.bg=function(a){for(var b in a)delete a[b]};
Object.Md=function(a,b){return void 0!==a[b]};Object.keys?Object.jf=function(a){return Object.keys(a).length}:(Object.keys=function(a){var b=[],c;for(c in a)b.push(c);return b},Object.jf=function(a){var b=0,c;for(c in a)b++;return b});Boolean.$="Boolean";Boolean.parse=function(a){return"true"==a.toLowerCase()};Number.$="Number";
Number.parse=function(a){return a&&a.length?0<=a.indexOf(".")||0<=a.indexOf("e")||(1>a.length?0:"f"==a.substr(a.length-1))||(1>a.length?0:"F"==a.substr(a.length-1))?parseFloat(a):parseInt(a,10):0};Number.prototype.Na=function(a){return k.oa(a)||0==a.length||"i"==a?this.toString():x(this,a,!1)};Number.prototype.Od=function(a){return k.oa(a)||0==a.length||"i"==a?this.toLocaleString():x(this,a,!0)};
Number.mc=function(a,b,c,e){var f=null;c=a.indexOf(c);0<c&&(f=a.substr(c),a=a.substr(0,c));(c=J(a,"-"))&&(a=a.substr(1));var g=0,h=b[g];if(a.length<h)return f?a+f:a;for(var m=a.length,l="",p=!1;!p;){var t=h,u=m-t;0>u&&(h+=u,t+=u,u=0,p=!0);if(!t)break;u=a.substr(u,t);l=l.length?u+e+l:u;m-=t;g<b.length-1&&(g++,h=b[g])}c&&(l="-"+l);return f?l+f:l};
function x(a,b,c){c=c?k.Ud.Df.qf:k.Ud.Ef.qf;var e="",f=-1;1<b.length&&(f=parseInt(b.substr(1)));b=b.charAt(0);switch(b){case "d":case "D":e=parseInt(Math.abs(a)).toString();-1!=f&&(e=N(e,f));0>a&&(e="-"+e);break;case "x":case "X":e=parseInt(Math.abs(a)).toString(16);"X"==b&&(e=e.toUpperCase());-1!=f&&(e=N(e,f));break;case "e":case "E":e=-1==f?a.toExponential():a.toExponential(f);"E"==b&&(e=e.toUpperCase());break;case "f":case "F":case "n":case "N":-1==f&&(f=c.zg);e=a.toFixed(f).toString();f&&"."!=
c.Rd&&(f=e.indexOf("."),e=e.substr(0,f)+c.Rd+e.substr(f+1));if("n"==b||"N"==b)e=Number.mc(e,c.Bg,c.Rd,c.Ag);break;case "c":case "C":-1==f&&(f=c.fg);e=Math.abs(a).toFixed(f).toString();f&&"."!=c.Gd&&(f=e.indexOf("."),e=e.substr(0,f)+c.Gd+e.substr(f+1));e=Number.mc(e,c.hg,c.Gd,c.gg);e=0>a?String.Na(c.ig,e):String.Na(c.jg,e);break;case "p":case "P":-1==f&&(f=c.Cg),e=(100*Math.abs(a)).toFixed(f).toString(),f&&"."!=c.Sd&&(f=e.indexOf("."),e=e.substr(0,f)+c.Sd+e.substr(f+1)),e=Number.mc(e,c.Eg,c.Sd,c.Dg),
e=0>a?String.Na(c.Fg,e):String.Na(c.Gg,e)}return e}String.$="String";String.Vd="";String.cf=function(a,b,c){c&&(a&&(a=a.toUpperCase()),b&&(b=b.toUpperCase()));a=a||"";b=b||"";return a==b?0:a<b?-1:1};String.concat=function(){return 2===arguments.length?arguments[0]+arguments[1]:Array.prototype.join.call(arguments,"")};String.lg=function(a,b,c){return 0==String.cf(a,b,c)};
String.gd=function(a,b,c){String.hd||(String.hd=/(\{[^\}^\{]+\})/g);return a.replace(String.hd,function(a,f){var g=b[parseInt(f.substr(1))+1];if(k.oa(g))return"";if(g.Na){var h=null,m=f.indexOf(":");0<m&&(h=f.substring(m+1,f.length-1));return c?g.Od(h):g.Na(h)}return c?g.toLocaleString():g.toString()})};String.Na=function(a){return String.gd(a,arguments,!1)};String.ff=function(a,b){for(var c=a,e=1;e<b;e++)c+=a;return c};String.nf=function(a){return!a||!a.length};
String.Od=function(a){return String.gd(a,arguments,!0)};function N(a,b){return a.length<b?String.ff("0",b-a.length)+a:a}String.prototype.remove=function(a,b){return!b||a+b>this.length?this.substr(0,a):this.substr(0,a)+this.substr(a+b)};function J(a,b){return b.length?b.length>a.length?!1:a.substr(0,b.length)==b:!0}String.prototype.trim||(String.prototype.trim=function(){return this.replace(/\s*$/,"").replace(/^\s*/,"")});Array.$="Array";Array.Ib=[k.Gb];Array.prototype.add=function(a){this.push(a)};
Array.prototype.Dc=function(){return 1===this.length?[this[0]]:Array.apply(null,this)};Array.prototype.contains=function(a){return 0<=this.indexOf(a)};function Q(a){return a.length?a[a.Sf?0:a.length-1]:null}Array.prototype.every||(Array.prototype.every=function(a,b){for(var c=this.length,e=0;e<c;e++)if(e in this&&!a.call(b,this[e],e,this))return!1;return!0});
Array.prototype.filter||(Array.prototype.filter=function(a,b){for(var c=this.length,e=[],f=0;f<c;f++)if(f in this){var g=this[f];a.call(b,g,f,this)&&e.push(g)}return e});Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=this.length,e=0;e<c;e++)e in this&&a.call(b,this[e],e,this)});Array.prototype.Oa=function(){return new k.Eb(this)};Array.prototype.index=function(a,b){for(var c=this.length,e={},f=0;f<c;f++)if(f in this){var g=a.call(b,this[f],f);String.nf(g)||(e[g]=this[f])}return e};
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length;if(c)for(var e=b||0;e<c;e++)if(this[e]===a)return e;return-1});Array.prototype.map||(Array.prototype.map=function(a,b){for(var c=this.length,e=Array(c),f=0;f<c;f++)f in this&&(e[f]=a.call(b,this[f],f,this));return e});Array.parse=function(a){return eval("("+a+")")};Array.prototype.remove=function(a){a=this.indexOf(a);return 0<=a?(this.splice(a,1),!0):!1};Array.prototype.Gc=function(a){this.splice(a,1)};
Array.prototype.some||(Array.prototype.some=function(a,b){for(var c=this.length,e=0;e<c;e++)if(e in this&&a.call(b,this[e],e,this))return!0;return!1});Array.vf=function(a){return Array.prototype.slice.call(a)};RegExp.$="RegExp";RegExp.parse=function(a){if(J(a,"/")){var b=a.lastIndexOf("/");if(1<b)return RegExp(a.substring(1,b),a.substr(b+1))}return null};Error.$="Error";
Error.dg=function(a,b,c){a=Error(a);if(b)for(var e in b)a[e]=b[e];c&&(a.pg=c);if(!(k.oa(a.stack)||k.oa(a.fileName)||k.oa(a.lineNumber))){b=a.stack.split("\n");c=b[0];for(e=a.fileName+":"+a.lineNumber;!k.oa(c)&&-1===c.indexOf(e);)b.shift(),c=b[0];c=b[1];isNullOrUndefined(c)||(c=c.match(/@(.*):(\d+)$/),k.oa(c)||(b.shift(),a.stack=b.join("\n"),a.fileName=c[1],a.lineNumber=parseInt(c[2])))}return a};k.ja=d.ja||function(){};k.ja.$="Debug";
k.ja.writeln||(k.ja.writeln=function(a){d.console?d.console.debug?d.console.debug(a):d.console.log&&d.console.log(a):d.opera&&d.opera.postError&&d.opera.postError(a)});k.ja.fd=function(a){k.ja.writeln(a);eval("debugger;")};k.ja.assert=function(a,b){a||(b="Assert failed: "+b,confirm(b+"\r\n\r\nBreak into debugger?")&&k.ja.fd(b))};k.ja.mg=function(a){k.ja.fd(a)};d.w=Function;d.w.$="Type";d.Pc=function(a){this.$=a};d.Pc.prototype={fe:!0};
d.w.rf=function(){d.jc||(d.jc={});d.Tc||(d.Tc=[]);if(!d.jc.trn){for(var a=self,b=["trn"],c=0;c<b.length;c++){var e=b[c],f=a[e];f||(a[e]=f=new d.Pc(b.slice(0,c+1).join(".")),0==c&&d.Tc.add(f));a=f}d.jc.trn=a}};d.w.prototype.P=function(a,b,c){this.prototype.constructor=this;this.$=a;this.Qc=!0;this.Aa=b||Object;b&&(this.Hb=!0);if(c){this.Ib=[];for(var e=2;e<arguments.length;e++)c=arguments[e],this.Ib.add(c)}};function R(a,b){a.$=b;a.Sc=!0}
d.w.prototype.Hc=function(){if(this.Hb){var a=this.Aa;a.Hb&&a.Hc();for(var b in a.prototype){var c=a.prototype[b];this.prototype[b]||(this.prototype[b]=c)}delete this.Hb}};d.w.prototype.sf||(d.w.prototype.sf=d.w.prototype.Hc);function T(a,b){return k.oa(b)?!1:a==Object||b instanceof a?!0:U(a,d.w.hf(b))}
function U(a,b){if(a==Object||a==b)return!0;if(a.Qc)for(var c=b.Aa;c;){if(a==c)return!0;c=c.Aa}else if(a.Sc){var e=b.Ib;if(e&&e.contains(a))return!0;for(c=b.Aa;c;){if((e=c.Ib)&&e.contains(a))return!0;c=c.Aa}}return!1}d.w.rg=function(a){return!0==a.Qc};d.w.sg=function(a){return!0==a.ee};d.w.tg=function(a){return!0==a.ee&&!0==a.Rc};d.w.ug=function(a){return!0==a.Sc};d.w.vg=function(a){return!0==a.fe};d.w.$f=function(a,b){return T(b,a)};d.w.Jg=function(a,b){return T(b,a)?a:null};
d.w.hf=function(a){var b=null;try{b=a.constructor}catch(c){}b&&b.$||(b=Object);return b};d.w.lf=function(a){if(!a)return null;d.w.kc||(d.w.kc={});var b=d.w.kc[a];b||(b=eval(a),d.w.kc[a]=b);return b};d.w.parse=function(a){return d.w.lf(a)};k.hc=function(){};k.hc.P("Enum");
k.hc.parse=function(a,b){var c=a.prototype;if(a.Rc){for(var e=b.split("|"),f=0,g=!0,h=e.length-1;0<=h;h--){var m=e[h].trim(),l=!1;for(p in c)if(p===m){f|=c[p];l=!0;break}if(!l){g=!1;break}}if(g)return f}else for(var p in c)if(p===b)return c[p];throw"Invalid Enumeration Value";};
k.hc.Jf=function(a){var b=this.prototype;if(this.Rc&&0!==a){var c=[];for(e in b)b[e]&a&&(c.length&&c.add(" | "),c.add(e));if(!c.length)throw"Invalid Enumeration Value";return c.join("")}for(var e in b)if(b[e]===a)return e;throw"Invalid Enumeration Value";};k.H=function(){};k.H.P("Delegate");k.H.empty=function(){};k.H.ie=function(a,b,c){for(var e=0;e<a.length;e+=2)if(a[e]===b&&a[e+1]===c)return!0;return!1};
k.H.nc=function(a){function b(){if(2==a.length)return a[1].apply(a[0],arguments);for(var c=a.Dc(),b=0;b<c.length;b+=2)k.H.ie(a,c[b],c[b+1])&&c[b+1].apply(c[b],arguments);return null}b.na=a;return b};k.H.create=function(a,b){return a?k.H.nc([a,b]):b};k.H.cg=function(a,b){return a?b?k.H.nc((a.na?a.na:[null,a]).concat(b.na?b.na:[null,b])):a.na?a:k.H.create(null,a):b.na?b:k.H.create(null,b)};
k.H.remove=function(a,b){if(!a||a===b)return null;if(!b)return a;var c=a.na,e=null,f;b.na?(e=b.na[0],f=b.na[1]):f=b;for(var g=0;g<c.length;g+=2)if(c[g]===e&&c[g+1]===f){if(2==c.length)return null;c.splice(g,2);return k.H.nc(c)}return a};k.H.eg=function(a,b,c){c=c||"__"+(new Date).valueOf();self[c]=b?a:function(){try{delete self[c]}catch(b){self[c]=void 0}a.apply(null,arguments)};return c};k.H.kg=function(a){delete self[a]};k.H.ag=function(a){self[a]=k.H.empty};k.ib=function(){};k.ib.prototype={Pd:null};
k.ib.Oa=function(a){return a?a.Oa?a.Oa():new k.Eb(a):null};R(k.ib,"IEnumerator");k.Gb=function(){};k.Gb.prototype={Oa:null};R(k.Gb,"IEnumerable");k.Eb=function(a){this.Uc=a;this.Ea=-1;this.Hd=null};k.Eb.prototype={Pd:function(){this.Ea++;this.Hd=this.Uc[this.Ea];return this.Ea<this.Uc.length}};k.Eb.P("ArrayEnumerator",null,k.ib);k.Mc=function(){};k.Mc.prototype={ef:null};R(k.Mc,"IDisposable");k.Oc=function(a){this.Qe=k.oa(a)?[]:[a]};k.Oc.prototype={toString:function(a){return this.Qe.join(a||"")}};
k.Oc.P("StringBuilder");k.Fb=function(){};k.Fb.P("EventArgs");k.Fb.Vd=new k.Fb;d.XMLHttpRequest||(d.XMLHttpRequest=function(){for(var a=["Msxml2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++)try{return new ActiveXObject(a[b])}catch(c){}return null});k.Lc=function(){var a=k.Lc;a.Hb&&a.Hc();a.Aa.apply(this);this.cancel=!1};k.Lc.P("CancelEventArgs",k.Fb);k.ce=function(){};k.ce.P("Tuple");k.Z=function(){this.wb=null};k.Z.prototype={};k.Z.Ac=[];k.Z.Oe={ef:function(){k.Z.Ac.pop()}};
k.Z.Ig=function(a){k.Z.Ac.push(a);return k.Z.Oe};k.Z.ge=function(a){var b=k.Z.Ac,c=b.length;if(c){a=a||[];for(var e=0;e<c;e++){var f=b[e];a.contains(f)||a.push(f)}return a}return null};k.Z.He=function(a){for(var b=0,c=a.length;b<c;b++)a[b].qg()};k.Z.P("Observable");k.Nc=function(a){this.Ga=a||[];this.wb=null};
k.Nc.prototype={add:function(a){this.Ga.push(a);V(this)},contains:function(a){return this.Ga.contains(a)},Oa:function(){this.wb=k.Z.ge(this.wb);return this.Ga.Oa()},indexOf:function(a){return this.Ga.indexOf(a)},remove:function(a){return this.Ga.remove(a)?(V(this),!0):!1},Gc:function(a){this.Ga.Gc(a);V(this)},vf:function(){return this.Ga}};function V(a){var b=a.wb;b&&(a.wb=null,k.Z.He(b))}k.Nc.P("ObservableCollection",null,k.Gb);k.Wd=function(){};R(k.Wd,"IApplication");k.Xd=function(){};R(k.Xd,"IContainer");
k.$d=function(){};R(k.$d,"IObjectFactory");k.Yd=function(){};R(k.Yd,"IEventManager");k.Zd=function(){};R(k.Zd,"IInitializable");(function(a){function b(a,b,f,g,h,m){this.za=16;this.be=288;this.status=0;this.root=null;this.qa=0;var l=Array(this.za+1),p,w,D,s,q,r,E,F=Array(this.za+1),C,B,A,y=new c,K=Array(this.za);s=Array(this.be);var z,G=Array(this.za+1),H,I,L;L=this.root=null;for(q=0;q<l.length;q++)l[q]=0;for(q=0;q<F.length;q++)F[q]=0;for(q=0;q<K.length;q++)K[q]=null;for(q=0;q<s.length;q++)s[q]=0;for(q=0;q<G.length;q++)G[q]=0;p=256<b?a[256]:this.za;C=a;B=0;q=b;do l[C[B]]++,B++;while(0<--q);if(l[0]==b)this.root=null,this.status=
this.qa=0;else{for(r=1;r<=this.za&&0==l[r];r++);E=r;m<r&&(m=r);for(q=this.za;0!=q&&0==l[q];q--);D=q;m>q&&(m=q);for(H=1<<r;r<q;r++,H<<=1)if(0>(H-=l[r])){this.status=2;this.qa=m;return}if(0>(H-=l[q]))this.status=2,this.qa=m;else{l[q]+=H;G[1]=r=0;C=l;B=1;for(A=2;0<--q;)G[A++]=r+=C[B++];C=a;q=B=0;do 0!=(r=C[B++])&&(s[G[r]++]=q);while(++q<b);b=G[D];G[0]=q=0;C=s;B=0;s=-1;z=F[0]=0;A=null;for(I=0;E<=D;E++)for(a=l[E];0<a--;){for(;E>z+F[1+s];){z+=F[1+s];s++;I=(I=D-z)>m?m:I;if((w=1<<(r=E-z))>a+1)for(w-=a+1,
A=E;++r<I&&!((w<<=1)<=l[++A]);)w-=l[A];z+r>p&&z<p&&(r=p-z);I=1<<r;F[1+s]=r;A=Array(I);for(w=0;w<I;w++)A[w]=new c;L=null==L?this.root=new e:L.next=new e;L.next=null;L.list=A;K[s]=A;0<s&&(G[s]=q,y.ha=F[s],y.ea=16+r,y.Qa=A,r=(q&(1<<z)-1)>>z-F[s],K[s-1][r].ea=y.ea,K[s-1][r].ha=y.ha,K[s-1][r].pa=y.pa,K[s-1][r].Qa=y.Qa)}y.ha=E-z;B>=b?y.ea=99:C[B]<f?(y.ea=256>C[B]?16:15,y.pa=C[B++]):(y.ea=h[C[B]-f],y.pa=g[C[B++]-f]);w=1<<E-z;for(r=q>>z;r<I;r+=w)A[r].ea=y.ea,A[r].ha=y.ha,A[r].pa=y.pa,A[r].Qa=y.Qa;for(r=1<<
E-1;0!=(q&r);r>>=1)q^=r;for(q^=r;(q&(1<<z)-1)!=G[s];)z-=F[s],s--}this.qa=F[1];this.status=0!=H&&1!=D?1:0}}}function c(){this.pa=this.ha=this.ea=0;this.Qa=null}function e(){this.list=this.next=null}var f=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],g=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],h=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],m=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,
1537,2049,3073,4097,6145,8193,12289,16385,24577],l=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],p=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];a.Ua||(a.Ua={});a.Ua.ic=function(a){this.Bf();this.fc=a;this.gc=0};a.Ua.ic.prototype={Jd:function(a){for(var c,b=Array(1024),e=[],f=0;f<a&&0<(c=this.Af(b,0,b.length));)e[e.length]=String.fromCharCode.apply(null,b.slice(0,c)),f+=c;return f?(this.fc=this.fc.slice(this.gc),this.gc=0,e.join("")):""},wf:function(){return this.fc.length==
this.gc?-1:this.fc.charCodeAt(this.gc++)&255},D:function(a){for(;this.Ra<a;)this.hb|=this.wf()<<this.Ra,this.Ra+=8},G:function(a){return this.hb&f[a]},C:function(a){this.hb>>=a;this.Ra-=a},ec:function(a,c,b){var e,f,g;if(0==b)return 0;for(g=0;;){this.D(this.ia);f=this.ya.list[this.G(this.ia)];for(e=f.ea;16<e;){if(99==e)return-1;this.C(f.ha);e-=16;this.D(e);f=f.Qa[this.G(e)];e=f.ea}this.C(f.ha);if(16==e)this.S&=32767,a[c+g++]=this.xa[this.S++]=f.pa;else{if(15==e)break;this.D(e);this.Y=f.pa+this.G(e);
this.C(e);this.D(this.gb);f=this.Td.list[this.G(this.gb)];for(e=f.ea;16<e;){if(99==e)return-1;this.C(f.ha);e-=16;this.D(e);f=f.Qa[this.G(e)];e=f.ea}this.C(f.ha);this.D(e);this.Sa=this.S-f.pa-this.G(e);for(this.C(e);0<this.Y&&g<b;)this.Y--,this.Sa&=32767,this.S&=32767,a[c+g++]=this.xa[this.S++]=this.xa[this.Sa++]}if(g==b)return b}this.wa=-1;return g},Cf:function(a,c,b){var e;e=this.Ra&7;this.C(e);this.D(16);e=this.G(16);this.C(16);this.D(16);if(e!=(~this.hb&65535))return-1;this.C(16);this.Y=e;for(e=
0;0<this.Y&&e<b;)this.Y--,this.S&=32767,this.D(8),a[c+e++]=this.xa[this.S++]=this.G(8),this.C(8);0==this.Y&&(this.wa=-1);return e},zf:function(a,c,e){if(null==this.dc){var f,n=Array(288);for(f=0;144>f;f++)n[f]=8;for(;256>f;f++)n[f]=9;for(;280>f;f++)n[f]=7;for(;288>f;f++)n[f]=8;this.Kc=7;f=new b(n,288,257,g,h,this.Kc);if(0!=f.status)return alert("HufBuild error: "+f.status),-1;this.dc=f.root;this.Kc=f.qa;for(f=0;30>f;f++)n[f]=5;this.Jc=5;f=new b(n,30,0,m,l,this.Jc);if(1<f.status)return this.dc=null,
alert("HufBuild error: "+f.status),-1;this.xf=f.root;this.Jc=f.qa}this.ya=this.dc;this.Td=this.xf;this.ia=this.Kc;this.gb=this.Jc;return this.ec(a,c,e)},yf:function(a,c,e){var f,n,O,P,S,w,D,s=Array(316);for(f=0;f<s.length;f++)s[f]=0;this.D(5);w=257+this.G(5);this.C(5);this.D(5);D=1+this.G(5);this.C(5);this.D(4);f=4+this.G(4);this.C(4);if(286<w||30<D)return-1;for(n=0;n<f;n++)this.D(3),s[p[n]]=this.G(3),this.C(3);for(;19>n;n++)s[p[n]]=0;this.ia=7;n=new b(s,19,19,null,null,this.ia);if(0!=n.status)return-1;
this.ya=n.root;this.ia=n.qa;P=w+D;for(f=O=0;f<P;)if(this.D(this.ia),S=this.ya.list[this.G(this.ia)],n=S.ha,this.C(n),n=S.pa,16>n)s[f++]=O=n;else if(16==n){this.D(2);n=3+this.G(2);this.C(2);if(f+n>P)return-1;for(;0<n--;)s[f++]=O}else{17==n?(this.D(3),n=3+this.G(3),this.C(3)):(this.D(7),n=11+this.G(7),this.C(7));if(f+n>P)return-1;for(;0<n--;)s[f++]=0;O=0}this.ia=9;n=new b(s,w,257,g,h,this.ia);0==this.ia&&(n.status=1);if(0!=n.status)return-1;this.ya=n.root;this.ia=n.qa;for(f=0;f<D;f++)s[f]=s[f+w];this.gb=
6;n=new b(s,D,0,m,l,this.gb);this.Td=n.root;this.gb=n.qa;return 0==this.gb&&257<w||0!=n.status?-1:this.ec(a,c,e)},Bf:function(){null==this.xa&&(this.xa=Array(65536));this.Ra=this.hb=this.S=0;this.wa=-1;this.cc=!1;this.Y=this.Sa=0;this.dc=this.ya=null},Af:function(a,c,b){var e,f;for(e=0;e<b&&(!this.cc||-1!=this.wa);){if(0<this.Y){if(0!=this.wa)for(;0<this.Y&&e<b;)this.Y--,this.Sa&=32767,this.S&=32767,a[c+e++]=this.xa[this.S++]=this.xa[this.Sa++];else{for(;0<this.Y&&e<b;)this.Y--,this.S&=32767,this.D(8),
a[c+e++]=this.xa[this.S++]=this.G(8),this.C(8);0==this.Y&&(this.wa=-1)}if(e==b)break}if(-1==this.wa){if(this.cc)break;this.D(1);0!=this.G(1)&&(this.cc=!0);this.C(1);this.D(2);this.wa=this.G(2);this.C(2);this.ya=null;this.Y=0}switch(this.wa){case 0:f=this.Cf(a,c+e,b-e);break;case 1:f=null!=this.ya?this.ec(a,c+e,b-e):this.zf(a,c+e,b-e);break;case 2:f=null!=this.ya?this.ec(a,c+e,b-e):this.yf(a,c+e,b-e);break;default:f=-1}if(-1==f)return this.cc?0:-1;e+=f}return e}};a.Ua.og=function(c){return(new a.Ua.ic(c)).Jd(4E7)}})(self);(function(a){function b(a){this.depth=this.index=0;this.v=a;this.location={start:0,Zb:1,$b:1,end:a.length,empty:!0};this.Cb=[this.location];this.Fc=!1;"?"===this.v.charAt(1)&&this.Ld();this.location.empty=!1}b.prototype={advance:function(){this.va=null;this.Ld();var a=this.location.start;++a;this.location.empty=!1;if("/"!==this.v.charAt(a))return this.location.empty="/"===this.v.charAt(this.v.indexOf(">",a)-1),!0;this.location.end=!0;return!1},df:function(a){if(a)return a.split("&quot;").join('"').split("&lt;").join("<").split("&gt;").join(">").split("&amp;").join("&")},
Nd:function(){var a=this.location.start+1,b=this.v.indexOf(">",a);this.location.empty&&--b;a=this.v.substring(a,b);this.va={};b=a.indexOf(" ");if(-1!==b){this.Id=a.substring(0,b);for(var a=a.slice(b),a=a.split('"'),b=a.length-1,f=0;f<b;++f){var g=a[f],h=a[++f];this.va[g.substring(1,g.length-1)]=h}}else this.Id=a},Ld:function(){if(this.Fc)this.Fc=!1,this.location.start=this.v.indexOf("<",this.location.start+1);else{var a=this.location.Zb;if(!this.location.empty)for(var b=this.location.$b;0<b;)a=this.v.indexOf("<",
a),"/"===this.v.charAt(++a)?--b:(a=this.v.indexOf(">",a),"/"!==this.v.charAt(a-1)&&++b);this.location.start=this.v.indexOf("<",a)}this.location.Zb=this.location.start+1;this.location.$b=1},ac:function(){this.v.ac&&this.v.ac(this.location.start)},A:function(){null!==this.va&&"undefined"!==typeof this.va||this.Nd();return this.Id},s:function(){++this.depth;this.location={start:this.location.start};this.Cb[this.Cb.length]=this.location;this.Fc=!0},p:function(){--this.depth;this.va=null;var a=this.location.Zb,
b=this.location.$b,f=this.location.empty,g=this.location.end;this.Cb.pop();this.location=this.Cb[this.Cb.length-1];this.location.Zb=a;this.location.$b=g?0:f?b:b+1},O:function(){return this.location.empty?!0:"/"===this.v.charAt(this.v.indexOf("<",this.location.start+1)+1)},q:function(a){null!==this.va&&"undefined"!==typeof this.va||this.Nd();return this.df(this.va[a])}};a.de=b})(self);d=self;self.w.rf();
d.trn.a=function(a){this.Yb=!1;this.vd=1E4;this.Ia={};this.Ma=this.vb=0;this.B=[];this.ca=[];this.ca.add({});this.ub=0;this.c=a;this.zd=this.Db("Width");this.yd=this.Db("Height");this.B.push(d.trn.Da.mf(this.zd,this.yd));this.R="c."+d.trn.a.d[d.trn.a.xe]+"();";this.ma="c."+d.trn.a.d[d.trn.a.we]+"();";this.W=!1;this.Ie=-1<navigator.userAgent.indexOf("Android")&&-1===navigator.userAgent.indexOf("Chrome")&&-1===navigator.userAgent.indexOf("Firefox");this.b="";this.c.s();this.c.advance();a=this.c.A();
d.trn.a.g(a,"FixedPage.Resources")&&(this.c.s(),this.c.advance(),this.Dd(),this.c.p());this.Ha=!1};d.trn.a.g=function(a,b){var c=d.trn.a.bf;return a===b?!0:a===c+b};d.trn.a.i=function(a){return d.trn.a.zb(a,3)};d.trn.a.Ab=function(a){return a.split("\\").join("\\\\").split('"').join('\\"')};d.trn.a.zb=function(a,b){var c=b,e=Math.abs(a);0.5>e&&(c=5E-4>e?5E-7>e?b+6:b+4:b+2);c=Math.pow(10,c);a=Math.round(a*c)/c;return a.toString()};d.trn.a.r=function(a,b){if(!a)throw Error(b);};d.trn.a.ng=function(a){return(new d.trn.a(a)).Be()};
d.trn.a.prototype={kd:function(a){return a+"."+d.trn.a.d[d.trn.a.ed]+"(t.m_a,t.m_b,t.m_c,t.m_d,t.m_h,t.m_v);"},je:function(a){var b="oc"+this.ta,c="ox"+this.ta;this.b+="var "+b+"=document.createElement('canvas');";this.b+=b+".width=b[2]";this.b+=";"+b+".height=b[3]";this.b+=";";this.b+="var "+c+"="+b+".getContext('2d');";b="o"+this.ta;this.b+="var "+b+"=function(c,ob){";this.b+="c."+d.trn.a.d[d.trn.a.Xc]+"();";this.b+="c."+d.trn.a.d[d.trn.a.qc]+"(0,0);";this.b+="c."+d.trn.a.d[d.trn.a.kb]+"(b[2],0);";
this.b+="c."+d.trn.a.d[d.trn.a.kb]+"(b[2],b[3]);";this.b+="c."+d.trn.a.d[d.trn.a.kb]+"(0,b[3]);";this.b+="c."+d.trn.a.d[d.trn.a.Yc]+"();";this.b+="c."+d.trn.a.d[d.trn.a.Lb]+"(-b[0],-b[1]);";this.b+=this.kd("c");var e=this.mb(),f=this.c.q("RenderTransform");if(null!=f){var g=new d.trn.m;g.Q(f);e.Ba(g)}this.b+=e.nb();this.b+=a;this.b+="};";this.b+=b+"("+c+",b);";return c},Ee:function(a){var b="t"+this.ta;this.b+=this.sd("var "+b+"=function(c,ob)");var c="tx"+this.ta;this.b+=a+".width=b[2];";this.b+=
a+".height=b[3];";this.b+="var "+c+"="+a+".getContext('2d');";a=this.mb();this.b+=c+"."+d.trn.a.d[d.trn.a.Lb]+"(-b[0],-b[1]);";this.b+=this.kd(c);this.b+=a.od(c);this.b+=b+"("+c+",b);";return c},oc:function(a){var b,c=this.Ae(),e=this.c.A();d.trn.a.g(e,"Path")?b=this.tc():d.trn.a.g(e,"Canvas")?b=this.Mb():d.trn.a.g(e,"Glyphs")?b=this.sc():(b=null,d.trn.a.r(!1,"Invalid Element "+e));b.eb(c);if(b.of()){var c="m"+ ++this.ta,e="d"+this.ta,f="tc"+this.ta;this.b+="var b=["+d.trn.a.i(b.k)+","+d.trn.a.i(b.l)+
","+d.trn.a.i(b.k+b.u)+","+d.trn.a.i(b.l+b.t)+"];";this.b+="var x1=b[0]*t.m_a + b[1]*t.m_c + t.m_h;";this.b+="var y1=b[0]*t.m_b + b[1]*t.m_d + t.m_v;";this.b+="var x2=b[2]*t.m_a + b[3]*t.m_c + t.m_h;";this.b+="var y2=b[2]*t.m_b + b[3]*t.m_d + t.m_v;";this.b+="if(x1<x2){b[0]=Math.floor(x1);b[2]=Math.ceil(x2-x1);}else{b[2]=Math.ceil(x1-x2);b[0]=Math.floor(x2);}";this.b+="if(y1<y2){b[1]=Math.floor(y1);b[3]=Math.ceil(y2-y1);}else{b[3]=Math.ceil(y1-y2);b[1]=Math.floor(y2);}";this.b+="var "+f+"=document.createElement('canvas');";
b=this.Ee(f);a=this.je(a);this.b+="var "+c+"="+a+"."+d.trn.a.d[d.trn.a.ad]+"(0,0,b[2],b[3]);";this.b+="var "+e+"="+b+"."+d.trn.a.d[d.trn.a.ad]+"(0,0,b[2],b[3]);";this.b+="var m = b[3]*b[2]<<2;";this.b+="for(var s=3;s<m;s+=4){";this.b+=e+".data[s]*=";this.b+=c+".data[s]/255;";this.b+="}";this.b+=b+"."+d.trn.a.d[d.trn.a.ue]+"("+e+",0,0);";this.b+=this.R;this.b+="c."+d.trn.a.d[d.trn.a.ye]+"(1,0,0,1,b[0]-ob[0],b[1]-ob[1]);";this.b+="c."+d.trn.a.d[d.trn.a.$c]+"("+f+",0,0);";this.b+=this.ma}else this.W=
!1},Mb:function(){var a=new d.trn.V;this.N();var b=this.c.q("RenderTransform");if(null!=b){var c=new d.trn.m;c.Q(b);this.I(c)}b=this.c.q("Clip");null!=b&&(a=this.sa(b));b=null;if(!this.c.O()){for(this.c.s();this.c.advance();)c=this.c.A(),d.trn.a.g(c,"Canvas.Clip")?(d.trn.a.r(!this.c.O(),"Canvas.Clip: Must contain PathGeometry element"),this.c.s(),this.c.advance()&&(c=new d.trn.m,c.Q(this.n("Transform")),this.I(c),a.eb(this.sa(this.n("Figures"))),c=c.pb(),this.I(c)),this.c.p()):d.trn.a.g(c,"Path")?
null!=b?b.Ic(this.tc()):b=this.tc():d.trn.a.g(c,"Glyphs")?null!=b?b.Ic(this.sc()):b=this.sc():d.trn.a.g(c,"Canvas")&&(null!=b?b.Ic(this.Mb()):b=this.Mb());this.c.p()}null!=b&&a.eb(b);this.da();return a},Re:function(){var a=this.Bc();a||(this.b+=this.R,this.N());var b=null,c=this.c.q("OpacityMask");null!=c&&(b=this.Ya(c,!0,"c."+d.trn.a.d[d.trn.a.Wa]+"();"));if(!this.c.O()){for(this.c.s();this.c.advance();)if(c=this.c.A(),d.trn.a.g(c,"Canvas.Resources"))this.c.O()?d.trn.a.r(!1,"Canvas.Resources must contain ResourceDictionary element"):
(this.c.s(),this.c.advance(),this.Dd(),this.c.p());else if(d.trn.a.g(c,"Canvas.Clip"))d.trn.a.r(!this.c.O(),"Canvas.Clip: Must contain PathGeometry element"),this.c.s(),this.c.advance()&&(a||(this.b+=this.R,a=!0,this.N()),c=new d.trn.m,c.Q(this.n("Transform")),this.b+=this.I(c),d.trn.a.r(d.trn.a.g(this.c.A(),"PathGeometry"),"Path.Clip must contain PathGeometry"),this.Wb(this.n("Figures")),c=c.pb(),this.b+=this.I(c)),this.c.p();else if(d.trn.a.g(c,"Canvas.OpacityMask"))this.W?this.W=!1:(this.c.s(),
this.c.advance(),b=this.Xa("c."+d.trn.a.d[d.trn.a.ka],"c."+d.trn.a.d[d.trn.a.Wa]+"();",new d.trn.m),this.c.p(),this.W=!0);else if(d.trn.a.g(c,"Path")||d.trn.a.g(c,"Glyphs")||d.trn.a.g(c,"Canvas")){if(null!=b){this.xb();this.c.p();this.W=!0;this.oc(b);return}this.Ha=!1;break}this.Ha&&this.c.p()}this.Ha&&this.xb()},xb:function(){this.b+=this.ma;this.da()},Db:function(a){a=this.c.q(a);d.trn.a.r(null!=a,this.c.A()+": "+a+" is not defined");return parseFloat(a)},ra:function(a,b){a=this.c.q(a);return null!=
a?parseFloat(a):b},n:function(a){a=this.c.q(a);d.trn.a.r(null!=a,this.c.A()+": "+a+" is not defined");return a},fb:function(a,b){a=this.c.q(a);return null!=a?a:b},Kd:function(){var a;a=this.c.q("x:Key");d.trn.a.r(null!=a,"Key must be defined for elements in a resource dictionary");return a},Bc:function(){0===this.Ma&&this.c.ac();var a=!1,b=this.ra("Opacity",1);1>b&&(a||(a=!0,this.b+=this.R,this.N()),this.b+=this.Va(b));b=this.c.q("RenderTransform");null!=b&&(a||(a=!0,this.b+=this.R,this.N()),this.Fa(b)?
this.b+=this.Ob(b):this.Bd(b));b=this.c.q("Clip");null!=b&&(a||(this.b+=this.R,this.N()),this.Wb(b),a=!0);return a},Wb:function(a){var b=!0;a&&"F"===a[0]&&(b=!1);this.Ed(b?"evenodd":"nonzero");this.Ge(this.sa(a));this.Cc(a);this.b+="c."+d.trn.a.d[d.trn.a.me]+"("+(b?"'evenodd'":"")+");"},Pe:function(a){var b=[];for(a=k.ib.Oa(a.split(";"));a.Pd();){var c=a.Hd,e=new d.trn.Ea,c=c.split(",");if(1<=c.length){if(0<c[0].length){var f=c[0].split(")");if(2<=f.length){var g=f[0].substr(1).split(":");e.vc=parseInt(g[0]);
e.wc=parseInt(g[1])}e.Sb=parseInt(f[f.length-1]);e.Ub=!0}2<=c.length&&(0<c[1].length&&(e.uc=parseFloat(c[1]),e.yc=!0),3<=c.length&&(0<c[2].length&&(e.Tb=parseFloat(c[2])),4<=c.length&&0<c[3].length&&(e.Vb=parseFloat(c[3]))))}b.add(e)}return b},Fe:function(){var a=this.n("UnicodeString"),b="",c=0,e=0,f=0,g=0;for(2<=a.length&&"{"===a.charAt(0)&&"}"===a.charAt(1)&&(a=a.substr(2));c<a.length;)e=a.charCodeAt(c),128>e?(b+=String.fromCharCode(e),c++):191<e&&224>e?(f=a.charCodeAt(c+1),b+=String.fromCharCode((e&
31)<<6|f&63),c+=2):(f=a.charCodeAt(c+1),g=a.charCodeAt(c+2),b+=String.fromCharCode((e&15)<<12|(f&63)<<6|g&63),c+=3);return b},sc:function(){var a=new d.trn.V,b=this.c.q("Clip");null!=b&&(a=this.sa(b));return a},rc:function(a){return this.Ie&&1===a.length?a+" ":a},Te:function(){var a=this.Bc(),b=this.Db("OriginX"),c=this.Db("OriginY"),e=this.n("FontUri");this.rb[e]=null;var f=this.Db("FontRenderingEmSize"),g=this.Pe(this.fb("Indices",""));if(200>f){f/=200;a||(this.N(),this.b+=this.R,a=!0);var h=new d.trn.m;
h.ob(f,0,0,f,b,c);f=200;b=c=0;this.b+=h.nb()}for(var h=0,m="p"+ ++this.Je,b="var "+m+"="+b+";",l=this.Fe(),p=0,t=0,u=f/100,v="",M=0;M<g.length;++M){var n=g[M];if(p!==n.Tb||t!==n.Vb)v&&(b+="c."+d.trn.a.d[d.trn.a.pc]+'("'+this.rc(d.trn.a.Ab(v))+'",'+m+(p?"+"+d.trn.a.i(p*u):"")+","+d.trn.a.i(c-t*u)+");",b+=m+"+=c."+d.trn.a.d[d.trn.a.cd]+'("'+d.trn.a.Ab(v)+'").'+d.trn.a.d[d.trn.a.ze]+";"),p=n.Tb,t=n.Vb,v="";n.yc?(b+="c."+d.trn.a.d[d.trn.a.pc]+'("'+this.rc(d.trn.a.Ab(v+(n.Ub?String.fromCharCode(n.Sb+57344):
l.substr(h,1))))+'",'+m+(p?"+"+d.trn.a.i(p*u):"")+","+d.trn.a.i(c-t*u)+");",b+=m+"+=",v&&(b+="c."+d.trn.a.d[d.trn.a.cd]+'("'+d.trn.a.Ab(v)+'").width+'),b+=d.trn.a.i(n.uc*u)+";",v=""):v+=n.Ub?String.fromCharCode(n.Sb+57344):l.substr(h,1);M+=n.wc-1;h+=n.vc}if(v||h<l.length)b+="c."+d.trn.a.d[d.trn.a.pc]+'("'+this.rc(d.trn.a.Ab(v+l.substr(h,l.length-h)))+'",'+m+","+d.trn.a.i(c)+");";g=c=null;h=this.c.q("OpacityMask");null!=h&&(g=this.Ya(h,!0,"c."+d.trn.a.d[d.trn.a.Wa]+"();"));if(!this.c.O()){for(this.c.s();this.c.advance();)h=
this.c.A(),d.trn.a.g(h,"Glyphs.Clip")?(d.trn.a.r(!this.c.O(),"Canvas.Clip: Must contain PathGeometry element"),this.c.s(),this.c.advance()&&(a||(a=!0,this.b+=this.R,this.N()),h=new d.trn.m,h.Q(this.n("Transform")),this.b+=h.nb(),d.trn.a.r(d.trn.a.g(this.c.A(),"PathGeometry"),"Path.Clip must contain PathGeometry"),m=this.n("Figures"),this.Wb(m),h=h.pb(),this.b+=h.nb()),this.c.p()):d.trn.a.g(h,"Glyphs.Fill")?(this.c.s(),this.c.advance(),c=this.Xa("c."+d.trn.a.d[d.trn.a.ka],b,new d.trn.m),this.c.p()):
d.trn.a.g(h,"Glyphs.OpacityMask")&&(this.W?this.W=!1:(this.c.s(),this.c.advance(),g=this.Xa("c."+d.trn.a.d[d.trn.a.ka],"c."+d.trn.a.d[d.trn.a.Wa]+"();",new d.trn.m),this.c.p(),this.W=!0));this.c.p()}null==g&&("otf"===e.substr(e.indexOf(".")+1)?(e=e.substr(0,e.length-4),e=parseInt(e.substr(7))):e=parseInt(e.substr(35,8),16),e="f"+e,Object.Md(this.Ia,e)?10>this.Ia[e].length&&(this.Ia[e]+=l.substr(0,10-this.Ia[e].length)):this.Ia[e]=l.substr(0,10),this.We(d.trn.a.i(f)+"px "+e),h=this.c.q("Fill"),null!=
h&&(c=this.Fa(h)?this.Ya(h,!0,b):this.Pb(h,"c."+d.trn.a.d[d.trn.a.ka],b)),null!=c&&(-1===c.indexOf(this.R)?this.Xb(c,b):this.Xb("c."+d.trn.a.d[d.trn.a.ka]+"='#000000';"+b,b)));a&&(this.b+=this.ma,this.da());null!=g&&(this.W=!0,this.oc(g))},ld:function(){var a=new String;this.c.s();d.trn.a.r(this.c.advance(),"Gradient brushes must contain GradientStops");for(this.c.s();this.c.advance();)var b=this.n("Color"),c=this.n("Offset"),a=a+("g."+d.trn.a.d[d.trn.a.ke]+"("+c+","+this.jd(b)+");");this.c.p();this.c.p();
return a},nd:function(a,b,c){var e=this.c.q("Transform"),f=new String,f=f+this.R;this.N();null!=e&&(c.Q(e),f+=this.I(c));c=this.ra("Opacity",1);1>c&&(f+=this.Va(c));c=this.n("StartPoint");e=this.n("EndPoint");f+="var g=c."+d.trn.a.d[d.trn.a.ne]+"("+c+","+e+");";f+=this.ld();f=f+(a+"=g;")+b;f+=this.ma;this.da();return f},pd:function(a,b,c){var e=this.c.q("Transform"),f=new String,g=this.n("RadiusX"),h=this.n("RadiusY"),m=this.n("GradientOrigin"),l=this.n("Center"),f=f+this.R;this.N();if(null!=e||g!==
h)null!=e&&c.Q(e),g!==h&&(e=parseFloat(g),h=parseFloat(h),d.trn.a.r(0<e&&0<h,"Invalid radius value"),h/=e,e=new d.trn.m,e.ob(1,0,0,h,0,0),c.Ba(e),l=l.split(","),l=d.trn.a.i(parseFloat(l[0]))+","+d.trn.a.i(parseFloat(l[1])/h),m=m.split(","),m=d.trn.a.i(parseFloat(m[0]))+","+d.trn.a.i(parseFloat(m[1])/h)),f+=this.I(c);c=this.ra("Opacity",1);1>c&&(f+=this.Va(c));f+="var g=c."+d.trn.a.d[d.trn.a.oe]+"("+m+",0,"+l+","+g+");";f+=this.ld();f=f+(a+"=g;")+b;f+=this.ma;this.da();return f},af:function(a){var b=
Q(this.B);a!==b.cb?(J(a,"c."+d.trn.a.d[d.trn.a.Kb]+"='")&&(b.cb=a),this.b+=a):this.b+="c."+d.trn.a.d[d.trn.a.lb]+"();"},Xb:function(a,b){var c=Q(this.B);a!==c.$a?(J(a,"c."+d.trn.a.d[d.trn.a.ka]+"='")&&(c.$a=a),this.b+=a):this.b+=b},Va:function(a){var b=Q(this.B);b.Ja*=a;a=""+("c."+d.trn.a.d[d.trn.a.qe]+"=");a+=d.trn.a.i(b.Ja);return a+";"},Ed:function(a){var b=Q(this.B);a!==b.Za&&(b.Za=a,this.b+='c.mozFillRule="'+a+'";')},Ze:function(a){var b=Q(this.B);a!==b.La&&(b.La=a,this.b+="c."+d.trn.a.d[d.trn.a.bd]+
"=",this.b+=d.trn.a.i(a),this.b+=";")},Xe:function(a){var b=Q(this.B);a!==b.ab&&(b.ab=a,this.b+="c."+d.trn.a.d[d.trn.a.re]+"='",this.b+=a,this.b+="';")},Ye:function(a){var b=Q(this.B);a!==b.Ka&&(b.Ka=a,this.b+="c."+d.trn.a.d[d.trn.a.se]+"='",this.b+=a,this.b+="';")},$e:function(a){var b=Q(this.B);a!==b.bb&&(b.bb=a,this.b+="c."+d.trn.a.d[d.trn.a.te]+"=",this.b+=d.trn.a.i(a),this.b+=";")},We:function(a){var b=Q(this.B);a!==b.tb&&(b.Ka=a,this.b+="c."+d.trn.a.d[d.trn.a.pe]+"='",this.b+=a,this.b+="';")},
I:function(a){Q(this.B).la.Ba(a);return a.nb()},mb:function(){return Q(this.B).la},Ae:function(){return Q(this.B).fa},Ge:function(a){Q(this.B).fa.eb(a)},N:function(a){a=a?Q(this.B).pf():Q(this.B).Dc();this.B.push(a);this.ca.add({})},da:function(){this.B.pop();this.ca.Gc(this.ca.length-1)},md:function(a,b,c){var e="",f=this.c.q("Transform"),e=e+this.R;this.N();var g=this.n("Viewbox"),h=new d.trn.V;h.Pa(g);var g=this.n("Viewport"),m=new d.trn.V;m.Pa(g);if(null!=f||h!==m){var g=m.u/h.u,l=m.t/h.t,p=m.k-
h.k*g,h=m.l-h.l*l;null!=f&&(this.Fa(f)?e+=this.Ob(f):c.Q(f));f=new d.trn.m;f.ob(g,0,0,l,p,h);c.Ba(f);e+=this.I(c)}c=this.ra("Opacity",1);1>c&&(e+=this.Va(c));c=this.fb("TileMode","None");f=this.n("ImageSource");this.rb[f]=null;f="i"+parseInt(f.split("/")[2]);e=e+a+("=c."+d.trn.a.d[d.trn.a.Zc]+"(window.ci."+f+",");e="None"===c?e+"'no-repeat'":e+"'repeat'";e+=");";e+=b;e+=this.ma;this.da();return e},Ce:function(){var a="",b=this.c.q("Transform"),a=a+this.R;this.N();var c=this.n("Viewbox"),e=new d.trn.V;
e.Pa(c);var c=this.n("Viewport"),f=new d.trn.V;f.Pa(c);if(null!=b||e!==f){var c=f.u/e.u,g=f.t/e.t,h=f.k-e.k*c,e=f.l-e.l*g,f=new d.trn.m;null!=b&&(this.Fa(b)?a+=this.Ob(b):f.Q(b));b=new d.trn.m;b.ob(c,0,0,g,h,e);f.Ba(b);a+=this.I(f)}b=this.ra("Opacity",1);1>b&&(a+=this.Va(b));this.fb("TileMode","None");b=this.n("ImageSource");this.rb[b]=null;a+="c."+d.trn.a.d[d.trn.a.$c]+"(window.ci."+("i"+parseInt(b.split("/")[2]))+", 0, 0);";a+=this.ma;this.da();return a},Ue:function(){this.Bd(this.c.q("Matrix"))},
Bd:function(a){if(null!=a){var b=new d.trn.m;b.Q(a);this.b+=this.I(b)}},h:function(a){for(var b=new String;","!==a.o.charAt(a.j)&&" "!==a.o.charAt(a.j)&&"\x00"!==a.o.charAt(a.j)&&("E"===a.o.charAt(a.j)||"e"===a.o.charAt(a.j)||!("A"<=a.o.charAt(a.j)&&"Z">=a.o.charAt(a.j)||"a"<=a.o.charAt(a.j)&&"z">=a.o.charAt(a.j)));)b+=a.o.charAt(a.j),++a.j;for(;" "===a.o.charAt(a.j)||","===a.o.charAt(a.j);)++a.j;return parseFloat(b)},sa:function(a){var b=" ",c=new d.trn.Jb(a,0,null,0),e=new d.trn.V,f=!0;e.Bb(0,0,
0,0);if(c.j<c.o.length)for(;" "===c.o.charAt(c.j);)c.j++;for(;c.j<a.length;){if("A"<=c.o.charAt(c.j)&&"Z">=c.o.charAt(c.j)||"a"<=c.o.charAt(c.j)&&"z">=c.o.charAt(c.j))b=c.o.charAt(c.j),c.j++;else{var g,h;"a">b&&("H"!==b&&(c.f=0),"V"!==b&&(c.e=0));switch(b){case "m":case "M":c.e+=this.h(c);c.f+=this.h(c);f?(e.Bb(c.e,c.f,c.e,c.f),f=!1):e.X(c.e,c.f);c.F=!1;break;case "l":case "L":c.e+=this.h(c);c.f+=this.h(c);e.X(c.e,c.f);c.F=!1;break;case "c":case "C":g=this.h(c)+c.e;h=this.h(c)+c.f;e.X(g,h);c.F=!0;
c.aa=this.h(c)+c.e;c.ba=this.h(c)+c.f;e.X(c.aa,c.ba);c.e+=this.h(c);c.f+=this.h(c);e.X(c.e,c.f);break;case "q":case "Q":g=this.h(c)+c.e;h=this.h(c)+c.f;e.X(g,h);c.e+=this.h(c);c.f+=this.h(c);e.X(c.e,c.f);c.F=!1;break;case "s":case "S":c.F||(c.aa=c.e,c.ba=c.f);g=2*c.e-c.aa;h=2*c.f-c.ba;e.X(g,h);c.F=!0;c.aa=this.h(c)+c.e;c.ba=this.h(c)+c.f;e.X(c.aa,c.ba);c.e+=this.h(c);c.f+=this.h(c);e.X(c.e,c.f);break;case "h":case "H":c.e+=this.h(c);e.X(c.e,c.f);c.F=!1;break;case "v":case "V":c.f+=this.h(c);e.X(c.e,
c.f);c.F=!1;break;default:this.h(c),c.F=!1}}for(;" "===a.charAt(c.j);)++c.j}return e.kf(this.mb())},tc:function(){var a=null;this.N();var b=this.c.q("RenderTransform");if(null!=b){var c=new d.trn.m;c.Q(b);this.I(c)}b=this.c.q("Clip");null!=b&&(a=this.sa(b));b=this.c.q("Data");if(!this.c.O()){for(this.c.s();this.c.advance();)if(c=this.c.A(),d.trn.a.g(c,"Path.Data")&&!this.c.O()){this.c.s();this.c.advance()&&(c=new d.trn.m,c.Q(this.n("Transform")),this.I(c),d.trn.a.r(d.trn.a.g(this.c.A(),"PathGeometry"),
"Path.Data must contain PathGeometry"),b=this.n("Figures"));this.c.p();break}else d.trn.a.g(c,"Path.Clip")&&(d.trn.a.r(!this.c.O(),"Path.Clip: Must contain PathGeometry element"),this.c.s(),this.c.advance()&&(c=new d.trn.m,c.Q(this.n("Transform")),this.I(c),a=this.sa(this.n("Figures")),c=c.pb(),this.I(c)),this.c.p());this.c.p()}null!=a?a.eb(this.sa(b)):a=this.sa(b);this.da();return a},qb:function(a,b,c){a.F=!1;if(null==a.ga)this.b+="c."+d.trn.a.d[d.trn.a.kb]+"("+d.trn.a.i(a.e)+","+d.trn.a.i(a.f)+
");";else for(var e=a.ga.length,f=a.e-b,g=a.f-c,h=g/f,m=Math.sqrt(f*f+g*g);1E-10<m;){var l=a.ga[a.Rb%e]-a.sb,p=l>m;p&&(a.sb+=m,l=m);if(f){var t=Math.sqrt(l*l/(1+h*h));0>f&&(t=-t);b+=t;c+=h*t}else c+=0<g?l:-l;this.b+="c."+(a.Rb%2?d.trn.a.d[d.trn.a.qc]:d.trn.a.d[d.trn.a.kb])+"("+d.trn.a.i(b)+","+d.trn.a.i(c)+");";m-=l;p||(++a.Rb,a.sb=0)}},Wc:function(a,b,c,e,f){a.F=!0;if(null==a.ga)this.b+="c."+d.trn.a.d[d.trn.a.le]+"("+d.trn.a.i(e)+","+d.trn.a.i(f)+","+d.trn.a.i(a.aa)+","+d.trn.a.i(a.ba)+","+d.trn.a.i(a.e)+
","+d.trn.a.i(a.f)+");";else{var g=this.mb().Ec(),g=(Math.abs(a.e-b)+Math.abs(a.f-c))/5*g,h=a.e,m=a.f;a.e=b;a.f=c;for(var g=1/parseInt(g),l=0;1>=l;l+=g){var p=1-l,t=a.e,u=a.f;a.e=p*p*p*b+3*p*p*l*e+3*p*l*l*a.aa+l*l*l*h;a.f=p*p*p*c+3*p*p*l*f+3*p*l*l*a.ba+l*l*l*m;this.qb(a,t,u)}}},he:function(a){if(null==a.ga)this.b+="c."+d.trn.a.d[d.trn.a.Yc]+"();";else{var b=a.e,c=a.f;a.e=a.wd;a.f=a.xd;this.qb(a,b,c)}},Ne:function(a){a.wd=a.e;a.xd=a.f;this.b+="c."+d.trn.a.d[d.trn.a.qc]+"("+d.trn.a.i(a.e)+","+d.trn.a.i(a.f)+
");";a.F=!1;a.Rb=a.xc;a.sb=a.ua},Se:function(a,b){var c,e,f=a.e,g=a.f;"a">b&&("H"!==b&&(a.f=0),"V"!==b&&(a.e=0));switch(b){case "m":case "M":a.e+=this.h(a);a.f+=this.h(a);this.Ne(a);break;case "l":case "L":a.e+=this.h(a);a.f+=this.h(a);this.qb(a,f,g);break;case "c":case "C":c=this.h(a)+a.e;e=this.h(a)+a.f;a.aa=this.h(a)+a.e;a.ba=this.h(a)+a.f;a.e+=this.h(a);a.f+=this.h(a);this.Wc(a,f,g,c,e);break;case "q":case "Q":c=this.h(a)+a.e;e=this.h(a)+a.f;a.e+=this.h(a);a.f+=this.h(a);this.b+="c."+d.trn.a.d[d.trn.a.ve]+
"("+d.trn.a.i(c)+","+d.trn.a.i(e)+","+d.trn.a.i(a.e)+","+d.trn.a.i(a.f)+");";a.F=!1;break;case "s":case "S":a.F||(a.aa=a.e,a.ba=a.f);c=2*a.e-a.aa;e=2*a.f-a.ba;a.F=!0;a.aa=this.h(a)+a.e;a.ba=this.h(a)+a.f;a.e+=this.h(a);a.f+=this.h(a);this.Wc(a,f,g,c,e);break;case "h":case "H":a.e+=this.h(a);this.qb(a,f,g);a.F=!1;break;case "v":case "V":a.f+=this.h(a);this.qb(a,f,g);a.F=!1;break;default:this.h(a),a.F=!1}},De:function(a){if("Flat"===a)return"butt";if("Square"===a)return"square";if("Round"===a||"Triangle"===
a)return"round";d.trn.a.r(!1,"Invalid line cap "+a);return""},Cc:function(a){this.Cd(a,null,0)},Cd:function(a,b,c){var e=" ";b=new d.trn.Jb(a,0,b,c);this.b+="c."+d.trn.a.d[d.trn.a.Xc]+"();";if(b.j<b.o.length)for(;" "===b.o.charAt(b.j);)b.j++;for(;b.j<a.length;)for("A"<=b.o.charAt(b.j)&&"Z">=b.o.charAt(b.j)||"a"<=b.o.charAt(b.j)&&"z">=b.o.charAt(b.j)?(e=b.o.charAt(b.j),"z"!==b.o.charAt(b.j)&&"Z"!==b.o.charAt(b.j)||this.he(b),b.j++):this.Se(b,e);" "===a.charAt(b.j);)++b.j},Ve:function(){var a=this.c.q("Data"),
b=!0;a&&"F"===a[0]&&(b=!1);var c="c."+d.trn.a.d[d.trn.a.Wa]+"("+(b?"'evenodd'":"")+");",e=!1,f=this.Bc(),g=this.c.q("Fill");null!=g&&(g=this.Fa(g)?this.Ya(g,!0,c):this.Pb(g,"c."+d.trn.a.d[d.trn.a.ka],c));var h=null,m=0,l=this.c.q("Stroke");null!=l&&(l=this.Fa(l)?this.Ya(l,!1,"c."+d.trn.a.d[d.trn.a.lb]+"();"):this.Pb(l,"c."+d.trn.a.d[d.trn.a.Kb],"c."+d.trn.a.d[d.trn.a.lb]+"();"));var p=this.ra("StrokeThickness",1),t=null,u=this.c.q("OpacityMask");null!=u&&(t=this.Ya(u,!0,"c."+d.trn.a.d[d.trn.a.Wa]+
"();"));m=null;u=new d.trn.m;if(!this.c.O()){for(this.c.s();this.c.advance();){var v=this.c.A();d.trn.a.g(v,"Path.Clip")?(d.trn.a.r(!this.c.O(),"Path.Clip: Must contain PathGeometry element"),this.c.s(),this.c.advance()&&(f||(f=!0,this.b+=this.R,this.N()),m=new d.trn.m,m.Q(this.n("Transform")),this.b+=this.I(m),d.trn.a.r(d.trn.a.g(this.c.A(),"PathGeometry"),"Path.Clip must contain PathGeometry"),v=this.n("Figures"),this.Wb(v),m=m.pb()),this.c.p()):d.trn.a.g(v,"Path.Data")&&!this.c.O()?(this.c.s(),
this.c.advance()&&(a=new d.trn.m,a.Q(this.n("Transform")),null!=m?m.Ba(a):m=a,this.b+=this.I(m),d.trn.a.r(d.trn.a.g(this.c.A(),"PathGeometry"),"Path.Data must contain PathGeometry"),a=this.n("Figures")),this.c.p()):d.trn.a.g(v,"Path.Fill")?(this.c.s(),this.c.advance(),null==t&&"ImageBrush"===this.c.A()&&(e=!0,this.b+=this.Ce()),g=this.Xa("c."+d.trn.a.d[d.trn.a.ka],c,new d.trn.m),this.c.p()):d.trn.a.g(v,"Path.OpacityMask")?this.W?this.W=!1:(this.c.s(),this.c.advance(),t=this.Xa("c."+d.trn.a.d[d.trn.a.ka],
c,new d.trn.m),this.c.p(),this.W=!0):d.trn.a.g(v,"Path.Stroke")&&(this.c.s(),this.c.advance(),l=this.Xa("c."+d.trn.a.d[d.trn.a.Kb],"c."+d.trn.a.d[d.trn.a.lb]+"();",u),this.c.p())}this.c.p()}if(null==t&&!e){d.trn.a.r(null!=a,"Paths must have Data defined");e=this.c.q("StrokeDashArray");if(null!=e)for(e=e.split(" "),h=Array(e.length),m=0;m<e.length;++m)h[m]=parseFloat(e[m])*p,h[m]||(h[m]=0.005);this.Ed(b?"evenodd":"nonzero");m=this.ra("StrokeDashOffset",0);null!=h&&null!=g&&(this.Cc(a),null!=g&&this.Xb(g,
c),g=null);this.Cd(a,h,m);null!=g&&this.Xb(g,c);null!=l&&(this.Ze(p/u.Ec()),this.Xe(this.De(this.fb("StrokeStartLineCap","Flat"))),this.Ye(this.fb("StrokeLineJoin","miter").toLowerCase()),this.$e(this.ra("StrokeMiterLimit",10)),this.af(l))}f&&(this.b+=this.ma,this.da());null!=t&&(this.W=!0,this.oc(t))},jd:function(a){var b=1,c=[255,255,255,255];if("#"===a.charAt(0)){if(7===a.length)return"'"+a+"'";var b="FF",e,f;d.trn.a.r(9===a.length,"Color "+a+" is invalid in a XOD file");b=a.substr(1,2);e=a.substr(3,
2);f=a.substr(5,2);a=a.substr(7,2);b=parseInt(b,16)/255;c[0]=parseInt(e,16);c[1]=parseInt(f,16);c[2]=parseInt(a,16)}else"s"===a.charAt(0)?(e=a.split("#")[1].split(","),3<e.length?(b=parseFloat(e[0]),f=255*parseFloat(e[1]),c[0]=parseInt(0>f?0:255<f?255:f),f=255*parseFloat(e[2]),f=0>f?0:255<f?255:f,c[1]=parseInt(f),f=255*parseFloat(e[3])):(f=255*parseFloat(e[0]),f=0>f?0:255<f?255:f,c[0]=parseInt(f),f=255*parseFloat(e[1]),f=0>f?0:255<f?255:f,c[1]=parseInt(f),f=255*parseFloat(e[2])),f=0>f?0:255<f?255:
f,c[2]=parseInt(f)):d.trn.a.r(!1,"Invalid color for a XOD file");return"'rgba("+c[0]+","+c[1]+","+c[2]+","+d.trn.a.i(b)+")'"},qd:function(a,b){return this.Pb(this.n("Color"),a,b)},Pb:function(a,b,c){return b+"="+this.jd(a)+";"+c},Qb:function(a){return this.sd("var "+a+"=function(c)")},sd:function(a){this.Ha=!1;var b=this.Ma,c=this.b;this.b="";this.Ma=this.c.depth;this.N(!0);this.b+=a+"{";if(!this.c.O())for(;this.zc(););this.da();this.b+="};";this.Ma=b;a=this.b;this.b=c;return a},rd:function(a,b,c){var e=
"",f=this.n("Viewbox"),g=new d.trn.V;g.Pa(f);var f=this.n("Viewport"),h=new d.trn.V;h.Pa(f);f=this.c.q("Transform");e+=this.R;this.N();var m;if(!this.c.O()){for(this.c.s();this.c.advance();){var l=this.c.A();d.trn.a.g(l,"VisualBrush.Visual")&&(this.c.s(),d.trn.a.r(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),this.N(!0),Q(this.B).la=new d.trn.m,m=this.Mb(),this.da(),this.c.p())}this.c.p()}if("undefined"!==typeof m){var l=h.k-g.k,p=h.l-g.l;g.eb(m);h=g;h.k+=l;h.l+=
p}if(null!=f||g!==h)l=h.u/g.u,m=h.t/g.t,p=h.k-g.k*l,h=h.l-g.l*m,null!=f&&(this.Fa(f)?e+=this.Ob(f):c.Q(f)),f=new d.trn.m,f.ob(l,0,0,m,p,h),c.Ba(f),e+=this.I(c);c=this.mb().Ec();h=Math.min(g.u,g.t);e+="var a=asc(t)*"+d.trn.a.i(c)+";if(a*"+h+"<2)a=2/"+h+";";if(g.k||g.l)e+="c."+d.trn.a.d[d.trn.a.Lb]+"("+d.trn.a.i(g.k)+","+d.trn.a.i(g.l)+");";e+="c."+d.trn.a.d[d.trn.a.dd]+"(1/a,1/a);";c=this.ra("Opacity",1);1>c&&(e+=this.Va(c));c=this.fb("TileMode","None");++this.vb;h="c"+this.vb;f="x"+this.vb;e=e+("var "+
h+"=document.createElement('canvas');")+(h+".width=");e+=g.u;e+="*a;"+h+".height=";e+=g.t;e+="*a;";e+="var "+f+"="+h+".getContext('2d');";e+=f+"."+d.trn.a.d[d.trn.a.dd]+"(a,a);";if(g.k||g.l)e+=f+"."+d.trn.a.d[d.trn.a.Lb]+"("+d.trn.a.i(-g.k)+","+d.trn.a.i(-g.l)+");";-1!==b.indexOf("c."+d.trn.a.d[d.trn.a.lb])&&(e+="c."+d.trn.a.d[d.trn.a.bd]+"=a*"+Q(this.B).La+";");g=this.c.q("Visual");g=null!=g?this.lc(g):"v"+this.vb;if(!this.c.O()){for(this.c.s();this.c.advance();)l=this.c.A(),d.trn.a.g(l,"VisualBrush.Visual")&&
(this.c.s(),d.trn.a.r(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),e+=this.Qb(g),this.c.p());this.c.p()}e+=g;e+="("+f+");";e+=a;e+="=c."+d.trn.a.d[d.trn.a.Zc]+"("+h+",";e="None"===c?e+"'no-repeat'":e+"'repeat'";e+=");";e+=b;e+=this.ma;this.da();return e},Fa:function(a){return"{"===a.charAt(0)},lc:function(a){var b=a.indexOf("StaticResource");d.trn.a.r(0<b,"Invalid resource reference: "+a);b+=15;a=a.substr(b,a.length-1-b);for(var b=null,c=this.ca.length-1;0<=c;--c)if(Object.Md(this.ca[c],
a)){b=this.ca[c][a];break}d.trn.a.r(null!=b,"Dictionary key "+a+" does not exist.");return b},Ya:function(a,b,c){return this.lc(a)+"(c,"+b+",'"+c+"');"},Ob:function(a){return this.lc(a)+"(c);"},zc:function(){var a=!0;if(this.Ha){if(this.c.depth===this.Ma)return d.trn.a.g(this.c.A(),"Canvas")&&this.xb(),!1;a=this.c.advance();if(!a){this.c.p();if(this.c.depth===this.Ma)return d.trn.a.g(this.c.A(),"Canvas")&&this.xb(),!1;this.xb();return!0}}this.Ha=!0;a=this.c.A();d.trn.a.g(a,"Canvas")?this.Re():d.trn.a.g(a,
"Path")?this.Ve():d.trn.a.g(a,"Glyphs")&&this.Te();return!0},Nb:function(){var a=this.Kd(),b="r"+this.ub.toString();++this.ub;return this.ca[this.ca.length-1][a]=b},Vc:function(){var a=this.Nb();this.b+="var "+a+"=function(c){\n"},jb:function(){var a=this.Kd(),b="r"+this.ub.toString();++this.ub;this.ca[this.ca.length-1][a]=b;this.b+="var "+b+"=function(c,s,o){"},Ca:function(){this.b+="};"},Xa:function(a,b,c){var e=this.c.A();if(d.trn.a.g(e,"ImageBrush"))return this.md(a,b,c);if(d.trn.a.g(e,"VisualBrush"))return this.rd(a,
b,c);if(d.trn.a.g(e,"LinearGradientBrush"))return this.nd(a,b,c);if(d.trn.a.g(e,"RadialGradientBrush"))return this.pd(a,b,c);if(d.trn.a.g(e,"SolidColorBrush"))return this.qd(a,b);d.trn.a.r(!1,"Invalid Brush Type: "+e);return""},Dd:function(){var a=this.c.A();if(d.trn.a.g(a,"ResourceDictionary")&&!this.c.O()){var b="c[(s?'"+d.trn.a.d[d.trn.a.ka]+"':'"+d.trn.a.d[d.trn.a.Kb]+"')]";for(this.c.s();this.c.advance();)a=this.c.A(),d.trn.a.g(a,"ImageBrush")?(this.jb(),this.b+=this.md(b,"eval(o);",new d.trn.m),
this.Ca()):d.trn.a.g(a,"LinearGradientBrush")?(this.jb(),this.b+=this.nd(b,"eval(o);",new d.trn.m),this.Ca()):d.trn.a.g(a,"RadialGradientBrush")?(this.jb(),this.b+=this.pd(b,"eval(o);",new d.trn.m),this.Ca()):d.trn.a.g(a,"VisualBrush")?(this.jb(),this.b+=this.rd(b,"eval(o);",new d.trn.m),this.Ca()):d.trn.a.g(a,"SolidColorBrush")?(this.jb(),this.b+=this.qd(b,"eval(o);"),this.Ca()):d.trn.a.g(a,"MatrixTransform")?(this.Vc(),this.Ue(),this.Ca()):d.trn.a.g(a,"PathGeometry")?(this.Vc(),this.Cc(this.n("Figures")),
this.Ca()):d.trn.a.g(a,"Path")?(a=this.Nb(),this.b+=this.Qb(a)):d.trn.a.g(a,"Glyphs")?(a=this.Nb(),this.b+=this.Qb(a)):d.trn.a.g(a,"Canvas")?(a=this.Nb(),this.b+=this.Qb(a)):d.trn.a.r(!1,"Resource type is invalid: "+a);this.c.p()}},Be:function(){for(var a="";!this.Yb;)a+=this.Qd();return a},Qd:function(){this.b+="var ob=[0,0];";for(this.rb={};this.b.length<this.vd&&this.zc(););this.zc()||(this.Yb=!0);var a=this.b;this.b="";return a},gf:function(){var a=[],b=this.rb,c;for(c in b)a.add(c.substr(1));
return a},Yb:!1,Ha:!1,R:null,ma:null,W:!1,b:null,zd:0,yd:0,ub:0,vb:0,ta:0,Je:0,vd:0,Ia:null,rb:null,Ma:0,ca:null,B:null,c:null};d.trn.Ea=function(){this.yc=this.Ub=!1;this.vc=this.wc=1;this.uc=this.Tb=this.Vb=this.Sb=0};d.trn.Ea.prototype={Ub:!1,yc:!1,vc:0,wc:0,Sb:0,uc:0,Tb:0,Vb:0};d.trn.Da=function(){};
d.trn.Da.mf=function(a,b){var c=new d.trn.Da;c.cb="black";c.$a="black";c.Za="nonzero";c.Ja=1;c.La=1;c.ab="butt";c.Ka="miter";c.bb=10;c.tb="10px sans-serif";c.la=new d.trn.m;c.fa=new d.trn.V;c.fa.Bb(0,0,a,b);return c};
d.trn.Da.prototype={Dc:function(){var a=new d.trn.Da;a.cb=this.cb;a.$a=this.$a;a.Za=this.Za;a.Ja=this.Ja;a.La=this.La;a.ab=this.ab;a.Ka=this.Ka;a.bb=this.bb;a.tb=this.tb;a.la=new d.trn.m;a.la.td(this.la);a.fa=new d.trn.V;a.fa.Bb(this.fa.k,this.fa.l,this.fa.u,this.fa.t);return a},pf:function(){var a=new d.trn.Da;a.cb="black";a.$a="black";a.Za="nonzero";a.Ja=1;a.La=1;a.ab="butt";a.Ka="miter";a.bb=10;a.tb="10px sans-serif";a.la=new d.trn.m;a.la.td(this.la);a.fa=new d.trn.V;return a},cb:null,$a:null,
Za:null,Ja:0,La:0,ab:null,Ka:null,bb:0,tb:null,la:null,fa:null};d.trn.Ta=function(a,b){this.x=a;this.y=b};d.trn.Ta.prototype={x:0,y:0};d.trn.V=function(){this.l=this.k=-1E6;this.u=this.t=2E6};
d.trn.V.prototype={Bb:function(a,b,c,e){this.k=a;this.l=b;this.u=c;this.t=e},of:function(){return 0<this.u&&0<this.t},Pa:function(a){a=a.split(",");d.trn.a.r(4===a.length,"Rectangles should contain 4 numbers");this.k=parseFloat(a[0]);this.l=parseFloat(a[1]);this.u=parseFloat(a[2]);this.t=parseFloat(a[3])},kf:function(a){if(a.ud())return this;var b=new d.trn.Ta(this.k,this.l),c=new d.trn.Ta(this.k,this.l+this.t),e=new d.trn.Ta(this.k+this.u,this.l),f=new d.trn.Ta(this.k+this.u,this.l+this.t);a.bc(b);
a.bc(c);a.bc(e);a.bc(f);a=Math.min(b.x,c.x,e.x,f.x);var g=Math.max(b.x,c.x,e.x,f.x),h=Math.min(b.y,c.y,e.y,f.y),b=Math.max(b.y,c.y,e.y,f.y),c=new d.trn.V;c.Bb(a,h,g-a,b-h);return c},X:function(a,b){a<this.k?(this.u+=this.k-a,this.k=a):a>this.k+this.u&&(this.u=a-this.k);b<this.l?(this.t+=this.l-b,this.l=b):b>this.l+this.t&&(this.t=b-this.l)},Ic:function(a){this.X(a.k,a.l);this.X(a.k+a.u,a.l+a.t)},eb:function(a){var b,c,e,f,g,h,m;b=this.k;c=this.k+this.u;e=this.l;f=this.l+this.t;g=a.k;h=a.k+a.u;m=a.l;
a=a.l+a.t;c<g||h<b||f<m||a<e?this.k=this.u=this.l=this.t=0:(this.k=b<g?g:b,this.u=(c<h?c:h)-this.k,this.l=e<m?m:e,this.t=(f<a?f:a)-this.l,this.u&&this.t||(this.k=this.u=this.l=this.t=0))},k:0,l:0,u:0,t:0};d.trn.m=function(){this.J=this.M=1;this.K=this.L=this.T=this.U=0};
d.trn.m.prototype={J:0,K:0,L:0,M:0,T:0,U:0,Q:function(a){var b=[1,0,0,1,0,0];a=a.split(",");for(var c=0;c<a.length&&6>c;++c)b[c]=parseFloat(a[c]);this.J=b[0];this.K=b[1];this.L=b[2];this.M=b[3];this.T=b[4];this.U=b[5]},ob:function(a,b,c,e,f,g){this.J=a;this.K=b;this.L=c;this.M=e;this.T=f;this.U=g},td:function(a){this.J=a.J;this.K=a.K;this.L=a.L;this.M=a.M;this.T=a.T;this.U=a.U},Ba:function(a){var b=this.J,c=this.K,e=this.L,f=this.M;this.J=a.J*b+a.K*e;this.K=a.J*c+a.K*f;this.L=a.L*b+a.M*e;this.M=a.L*
c+a.M*f;this.T=a.T*b+a.U*e+this.T;this.U=a.T*c+a.U*f+this.U},pb:function(){var a=new d.trn.m,b=this.J*this.M-this.K*this.L;if(!b)return a;a.J=this.M/b;a.L=-this.L/b;a.T=(this.L*this.U-this.T*this.M)/b;a.K=-this.K/b;a.M=this.J/b;a.U=-(this.J*this.U-this.T*this.K)/b;return a},bc:function(a){var b=a.x*this.K+a.y*this.M+this.U;a.x=a.x*this.J+a.y*this.L+this.T;a.y=b},Ec:function(){var a=0.707106781*this.J+0.707106781*this.K,b=0.707106781*this.L+0.707106781*this.M;return Math.sqrt(a*a+b*b)},ud:function(){return 1!==
this.J||this.K||this.L||1!==this.M||this.T||this.U?!1:!0},nb:function(){return this.od("c")},od:function(a){return this.ud()?"":a+"."+d.trn.a.d[d.trn.a.ed]+"("+d.trn.a.zb(this.J,4)+","+d.trn.a.zb(this.K,4)+","+d.trn.a.zb(this.L,4)+","+d.trn.a.zb(this.M,4)+","+d.trn.a.i(this.T)+","+d.trn.a.i(this.U)+");"}};
d.trn.Jb=function(a,b,c,e){this.o=a;this.j=b;this.e=this.f=0;this.F=!1;this.ga=c;if(null!=this.ga){for(b=a=0;b<this.ga.length;++b)a+=this.ga[b];this.ua=e%a;0>this.ua&&(this.ua+=a);for(b=this.xc=0;this.ua>this.ga[b];++b)this.ua-=this.ga[b],++this.xc}};d.trn.Jb.prototype={o:null,j:0,ga:null,Rb:0,sb:0,xc:0,ua:0,e:0,f:0,wd:0,xd:0,F:!1,aa:0,ba:0};d.trn.Ad=function(a,b,c){this.Le=a;this.Me=b;this.Ke=c};d.trn.Ad.prototype={Ke:0,Me:0,Le:0};d.trn.a.P("myglobs.trn.Converter");d.trn.Ea.P("myglobs.trn._index");
d.trn.Da.P("myglobs.trn._gState");d.trn.Ta.P("myglobs.trn.Point");d.trn.V.P("myglobs.trn._rect");d.trn.m.P("myglobs.trn._matrix2D");d.trn.Jb.P("myglobs.trn._abbrGeomItr");d.trn.Ad.P("myglobs.trn._pageInfo");d.trn.a.Kf="http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key";d.trn.a.Of="http://schemas.openxps.org/oxps/v1.0/resourcedictionary-key";d.trn.a.Vf="http://schemas.microsoft.com/winfx/2006/xaml";d.trn.a.bf="http://schemas.microsoft.com/xps/2005/06";d.trn.a.Wf="http://schemas.microsoft.com/winfx/2006/xaml/presentation";
d.trn.a.Pf="http://schemas.openxps.org/oxps/v1.0";d.trn.a.Yf="http://schemas.microsoft.com/xps/2005/06/documentstructure";d.trn.a.Nf="http://schemas.openxps.org/oxps/v1.0/documentstructure";d.trn.a.Tf="http://schemas.openxmlformats.org/package/2006/relationships";d.trn.a.Ff="http://schemas.openxmlformats.org/package/2006/content-types";d.trn.a.Lf="http://schemas.openxmlformats.org/markup-compatibility/2006";d.trn.a.Gf="http://schemas.openxmlformats.org/package/2006/metadata/core-properties";
d.trn.a.Hf="http://purl.org/dc/elements/1.1/";d.trn.a.If="http://purl.org/dc/terms/";d.trn.a.Xf="http://www.w3.org/XML/1998/namespace";d.trn.a.Uf="clr-namespace:PDFTron.SilverDox.Internal;assembly=SilverDox";d.trn.a.Zf="http://schemas.microsoft.com/xps/2005/06/restricted-font";d.trn.a.Qf="http://schemas.openxps.org/oxps/v1.0/restricted-font";d.trn.a.Mf="application/vnd.ms-package.obfuscated-opentype";d.trn.a.Rf="http://www.pdftron.com/silverdox/2010/09";d.trn.a.xe=0;d.trn.a.we=1;d.trn.a.ed=2;
d.trn.a.Lb=3;d.trn.a.bd=4;d.trn.a.re=5;d.trn.a.Kb=6;d.trn.a.ka=7;d.trn.a.qe=8;d.trn.a.ne=9;d.trn.a.oe=10;d.trn.a.Zc=11;d.trn.a.ke=12;d.trn.a.Xc=13;d.trn.a.Yc=14;d.trn.a.Wa=15;d.trn.a.lb=16;d.trn.a.me=17;d.trn.a.qc=18;d.trn.a.kb=19;d.trn.a.ve=20;d.trn.a.le=21;d.trn.a.pe=22;d.trn.a.pc=23;d.trn.a.cd=24;d.trn.a.ze=25;d.trn.a.te=26;d.trn.a.se=27;d.trn.a.$c=28;d.trn.a.ye=29;d.trn.a.ad=30;d.trn.a.ue=31;d.trn.a.dd=32;d.trn.a.d="SrtTwcsfaLRPAbzFXCMlqBnxmWijIZdDe".split("");self.trn.a||(self.trn=trn);function W(a){this.v="";this.uf=new self.Ua.ic(a);X(this);this.start=0}W.prototype={Fd:102400,ac:function(a){var b=a-this.start;b>W.prototype.Fd&&(this.v=this.v.slice(b),this.start=a)},indexOf:function(a,b){var c;b-=this.start;do c=this.v.indexOf(a,b);while(-1===c&&X(this));return c+this.start},charAt:function(a){a-=this.start;a>=this.v.length&&X(this);return this.v.charAt(a)},substring:function(a,b){a-=this.start;b-=this.start;return this.v.substring(a,b)}};
function X(a){var b=a.uf.Jd(W.prototype.Fd);return b.length?(a.v+=b,!0):!1}self.ae=W;
self.onmessage=function(a){switch(a.data.command){case "data":a=new self.de(new self.ae(a.data.dataString));self.yb=new self.trn.a(a);break;case "nextChunk":self.yb.Yb?(self.postMessage({command:"done"}),self.yb=null):(a=self.yb.Qd(),self.postMessage({command:"nextChunk",resources:self.yb.gf(),dataString:a}));break;case "cancel":self.yb=null;self.postMessage({command:"done"});break;default:throw Error("Unknown message command "+a.data.command);}};
