/**
 * settings.js
 * ======================
 * The model of the WebViewer Universal Viewer can be specified here.
 * The model contains all the data necessary to load the document and setup UI state of the viewer.
 * This could contain the URL to the xod document, URL to the annotation server, the default layout modes etc.
 * 
 * This file can be defined statically on the client side, or be dynmically generated by a web server.
 * 
 * 
 */

//Optional: Provide a server url here to fetch default settings, used for model.fetch();
//window.WebViewerUniversalInstance.model.url = "http://your.server/model";
//Or provide the default settings directly here:
window.WebViewerUniversalInstance.model.set(
        {
            documentUrl: "http://pdftron.s3.amazonaws.com/files/xod/NY_fun_list.xod",      //url to the xod document to load on start      
            //documentUrl: "http://local.mybookstore.com/lib/universal/Mimeo_QuickGuide_low.pdf.xod",
            serverUrl: "../html5/annotationHandler.ashx",    //server script for handling annotations
            annotationUser: new PDFTron.WebViewer.User("Guest", false),
            currentPageNumber: 0,
            pageCount: 0,
            zoomLevel: 0,
            fitMode: PDFTron.WebViewer.FitMode.Zoom,
            layoutMode: PDFTron.WebViewer.LayoutMode.SinglePage,
            toolMode: '',
            rotation: 0,
            webViewerLibPath: '..', //URL path to the WebViewer lib folder
            webViewerOptions: { //extra WebViewer options
                silverlightOptions: {
                    enableAnnotations: false //disable annotations if silverlight is loaded. 
                }
            }
        }
);
